{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "abe03dda",
   "metadata": {},
   "source": [
    "## PDP - Partial Depencency Plots"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "b1182a46",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import statsmodels.api as sm\n",
    "import sklearn.tree as DecisionTreeClassifier"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "7ec3abf1",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting pdpbox\n",
      "  Using cached PDPbox-0.2.1-py3-none-any.whl\n",
      "Requirement already satisfied: psutil in c:\\users\\aratr\\anaconda3\\lib\\site-packages (from pdpbox) (5.8.0)\n",
      "Requirement already satisfied: scipy in c:\\users\\aratr\\anaconda3\\lib\\site-packages (from pdpbox) (1.6.2)\n",
      "Requirement already satisfied: numpy in c:\\users\\aratr\\anaconda3\\lib\\site-packages (from pdpbox) (1.20.1)\n",
      "Requirement already satisfied: joblib in c:\\users\\aratr\\anaconda3\\lib\\site-packages (from pdpbox) (1.0.1)\n",
      "Collecting matplotlib==3.1.1\n",
      "  Using cached matplotlib-3.1.1.tar.gz (37.8 MB)\n",
      "  Preparing metadata (setup.py): started\n",
      "  Preparing metadata (setup.py): finished with status 'done'\n",
      "Requirement already satisfied: sklearn in c:\\users\\aratr\\anaconda3\\lib\\site-packages (from pdpbox) (0.0)\n",
      "Requirement already satisfied: pandas in c:\\users\\aratr\\anaconda3\\lib\\site-packages (from pdpbox) (1.2.4)\n",
      "Requirement already satisfied: cycler>=0.10 in c:\\users\\aratr\\anaconda3\\lib\\site-packages (from matplotlib==3.1.1->pdpbox) (0.10.0)\n",
      "Requirement already satisfied: kiwisolver>=1.0.1 in c:\\users\\aratr\\anaconda3\\lib\\site-packages (from matplotlib==3.1.1->pdpbox) (1.3.1)\n",
      "Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\\users\\aratr\\anaconda3\\lib\\site-packages (from matplotlib==3.1.1->pdpbox) (2.4.7)\n",
      "Requirement already satisfied: python-dateutil>=2.1 in c:\\users\\aratr\\anaconda3\\lib\\site-packages (from matplotlib==3.1.1->pdpbox) (2.8.1)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  error: subprocess-exited-with-error\n",
      "  \n",
      "  python setup.py bdist_wheel did not run successfully.\n",
      "  exit code: 1\n",
      "  \n",
      "  [55 lines of output]\n",
      "  ================================================================================\n",
      "  Edit setup.cfg to change the build options\n",
      "  \n",
      "  BUILDING MATPLOTLIB\n",
      "    matplotlib: yes [3.1.1]\n",
      "        python: yes [3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit\n",
      "                    (AMD64)]]\n",
      "      platform: yes [win32]\n",
      "  \n",
      "  OPTIONAL SUBPACKAGES\n",
      "   sample_data: yes [installing]\n",
      "         tests: no  [skipping due to configuration]\n",
      "  \n",
      "  OPTIONAL BACKEND EXTENSIONS\n",
      "           agg: yes [installing]\n",
      "         tkagg: yes [installing; run-time loading from Python Tcl/Tk]\n",
      "        macosx: no  [Mac OS-X only]\n",
      "  \n",
      "  OPTIONAL PACKAGE DATA\n",
      "          dlls: no  [skipping due to configuration]\n",
      "  \n",
      "  running bdist_wheel\n",
      "  running build\n",
      "  running build_py\n",
      "  UPDATING build\\lib.win-amd64-3.8\\matplotlib\\_version.py\n",
      "  set build\\lib.win-amd64-3.8\\matplotlib\\_version.py to '3.1.1'\n",
      "  running build_ext\n",
      "  building 'matplotlib.ft2font' extension\n",
      "  checkdep_freetype2.c\n",
      "  Compiling with FreeType version 2.10.4.\n",
      "  ft2font.cpp\n",
      "  src/ft2font.cpp(739): warning C4267: 'argument': conversion from 'size_t' to 'long', possible loss of data\n",
      "  ft2font_wrapper.cpp\n",
      "  src/ft2font_wrapper.cpp(54): warning C4244: 'argument': conversion from 'double' to 'unsigned long', possible loss of data\n",
      "  src/ft2font_wrapper.cpp(79): warning C4244: 'argument': conversion from 'double' to 'unsigned long', possible loss of data\n",
      "  src/ft2font_wrapper.cpp(98): warning C4244: 'argument': conversion from 'double' to 'unsigned long', possible loss of data"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pytz>=2017.3 in c:\\users\\aratr\\anaconda3\\lib\\site-packages (from pandas->pdpbox) (2021.1)\n",
      "Requirement already satisfied: scikit-learn in c:\\users\\aratr\\anaconda3\\lib\\site-packages (from sklearn->pdpbox) (0.24.1)\n",
      "Requirement already satisfied: six in c:\\users\\aratr\\anaconda3\\lib\\site-packages (from cycler>=0.10->matplotlib==3.1.1->pdpbox) (1.15.0)\n",
      "Requirement already satisfied: threadpoolctl>=2.0.0 in c:\\users\\aratr\\anaconda3\\lib\\site-packages (from scikit-learn->sklearn->pdpbox) (2.1.0)\n",
      "Building wheels for collected packages: matplotlib\n",
      "  Building wheel for matplotlib (setup.py): started\n",
      "  Building wheel for matplotlib (setup.py): finished with status 'error'\n",
      "  Running setup.py clean for matplotlib\n",
      "Failed to build matplotlib\n",
      "Installing collected packages: matplotlib, pdpbox\n",
      "  Attempting uninstall: matplotlib\n",
      "    Found existing installation: matplotlib 3.5.1\n",
      "    Uninstalling matplotlib-3.5.1:\n",
      "      Successfully uninstalled matplotlib-3.5.1\n",
      "  Running setup.py install for matplotlib: started\n",
      "  Running setup.py install for matplotlib: finished with status 'error'\n",
      "  Rolling back uninstall of matplotlib\n",
      "  Moving to c:\\users\\aratr\\anaconda3\\lib\\site-packages\\__pycache__\\pylab.cpython-38.pyc\n",
      "   from C:\\Users\\aratr\\AppData\\Local\\Temp\\pip-uninstall-6b_9b59m\\pylab.cpython-38.pyc\n",
      "  Moving to c:\\users\\aratr\\anaconda3\\lib\\site-packages\\matplotlib-3.5.1-py3.8-nspkg.pth\n",
      "   from C:\\Users\\aratr\\AppData\\Local\\Temp\\pip-uninstall-f_3_r1oz\\matplotlib-3.5.1-py3.8-nspkg.pth\n",
      "  Moving to c:\\users\\aratr\\anaconda3\\lib\\site-packages\\matplotlib-3.5.1.dist-info\\\n",
      "   from C:\\Users\\aratr\\anaconda3\\Lib\\site-packages\\~atplotlib-3.5.1.dist-info\n",
      "  Moving to c:\\users\\aratr\\anaconda3\\lib\\site-packages\\matplotlib\\\n",
      "   from C:\\Users\\aratr\\anaconda3\\Lib\\site-packages\\~atplotlib\n",
      "  Moving to c:\\users\\aratr\\anaconda3\\lib\\site-packages\\mpl_toolkits\\axes_grid1\\\n",
      "   from C:\\Users\\aratr\\anaconda3\\Lib\\site-packages\\mpl_toolkits\\~xes_grid1\n",
      "  Moving to c:\\users\\aratr\\anaconda3\\lib\\site-packages\\mpl_toolkits\\axes_grid\\\n",
      "   from C:\\Users\\aratr\\anaconda3\\Lib\\site-packages\\mpl_toolkits\\~xes_grid\n",
      "  Moving to c:\\users\\aratr\\anaconda3\\lib\\site-packages\\mpl_toolkits\\axisartist\\\n",
      "   from C:\\Users\\aratr\\anaconda3\\Lib\\site-packages\\mpl_toolkits\\~xisartist\n",
      "  Moving to c:\\users\\aratr\\anaconda3\\lib\\site-packages\\mpl_toolkits\\mplot3d\\\n",
      "   from C:\\Users\\aratr\\anaconda3\\Lib\\site-packages\\mpl_toolkits\\~plot3d\n",
      "  Moving to c:\\users\\aratr\\anaconda3\\lib\\site-packages\\mpl_toolkits\\tests\\\n",
      "   from C:\\Users\\aratr\\anaconda3\\Lib\\site-packages\\mpl_toolkits\\~ests\n",
      "  Moving to c:\\users\\aratr\\anaconda3\\lib\\site-packages\\pylab.py\n",
      "   from C:\\Users\\aratr\\AppData\\Local\\Temp\\pip-uninstall-f_3_r1oz\\pylab.py\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "  src/ft2font_wrapper.cpp(355): warning C4267: 'return': conversion from 'size_t' to 'unsigned long', possible loss of data\n",
      "  src/ft2font_wrapper.cpp(442): warning C4244: '=': conversion from 'Py_ssize_t' to 'FT_Long', possible loss of data\n",
      "  src/ft2font_wrapper.cpp(699): warning C4267: 'argument': conversion from 'size_t' to 'long', possible loss of data\n",
      "  src/ft2font_wrapper.cpp(902): warning C4244: 'argument': conversion from 'double' to 'int', possible loss of data\n",
      "  src/ft2font_wrapper.cpp(1767): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.\n",
      "  mplutils.cpp\n",
      "  py_converters.cpp\n",
      "     Creating library build\\temp.win-amd64-3.8\\Release\\src\\ft2font.cp38-win_amd64.lib and object build\\temp.win-amd64-3.8\\Release\\src\\ft2font.cp38-win_amd64.exp\n",
      "  Generating code\n",
      "  Finished generating code\n",
      "  building 'matplotlib._png' extension\n",
      "  _png.cpp\n",
      "  src/_png.cpp(335): warning C4244: 'argument': conversion from 'Py_ssize_t' to 'int', possible loss of data\n",
      "  src/_png.cpp(317): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.\n",
      "  checkdep_libpng.c\n",
      "  Compiling with libpng version 1.6.37.\n",
      "  mplutils.cpp\n",
      "  LINK : fatal error LNK1181: cannot open input file 'png.lib'\n",
      "  error: command 'C:\\\\Program Files\\\\Microsoft Visual Studio\\\\2022\\\\Community\\\\VC\\\\Tools\\\\MSVC\\\\14.30.30705\\\\bin\\\\HostX86\\\\x64\\\\link.exe' failed with exit code 1181\n",
      "  [end of output]\n",
      "  \n",
      "  note: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "  ERROR: Failed building wheel for matplotlib\n",
      "  error: subprocess-exited-with-error\n",
      "  \n",
      "  Running setup.py install for matplotlib did not run successfully.\n",
      "  exit code: 1\n",
      "  \n",
      "  [57 lines of output]\n",
      "  ================================================================================\n",
      "  Edit setup.cfg to change the build options\n",
      "  \n",
      "  BUILDING MATPLOTLIB\n",
      "    matplotlib: yes [3.1.1]\n",
      "        python: yes [3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit\n",
      "                    (AMD64)]]\n",
      "      platform: yes [win32]\n",
      "  \n",
      "  OPTIONAL SUBPACKAGES\n",
      "   sample_data: yes [installing]\n",
      "         tests: no  [skipping due to configuration]\n",
      "  \n",
      "  OPTIONAL BACKEND EXTENSIONS\n",
      "           agg: yes [installing]\n",
      "         tkagg: yes [installing; run-time loading from Python Tcl/Tk]\n",
      "        macosx: no  [Mac OS-X only]\n",
      "  \n",
      "  OPTIONAL PACKAGE DATA\n",
      "          dlls: no  [skipping due to configuration]\n",
      "  \n",
      "  running install\n",
      "  c:\\users\\aratr\\anaconda3\\lib\\site-packages\\setuptools\\command\\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.\n",
      "    warnings.warn(\n",
      "  running build\n",
      "  running build_py\n",
      "  UPDATING build\\lib.win-amd64-3.8\\matplotlib\\_version.py\n",
      "  set build\\lib.win-amd64-3.8\\matplotlib\\_version.py to '3.1.1'\n",
      "  running build_ext\n",
      "  building 'matplotlib.ft2font' extension\n",
      "  checkdep_freetype2.c\n",
      "  Compiling with FreeType version 2.10.4.\n",
      "  ft2font.cpp\n",
      "  src/ft2font.cpp(739): warning C4267: 'argument': conversion from 'size_t' to 'long', possible loss of data\n",
      "  ft2font_wrapper.cpp\n",
      "  src/ft2font_wrapper.cpp(54): warning C4244: 'argument': conversion from 'double' to 'unsigned long', possible loss of data\n",
      "  src/ft2font_wrapper.cpp(79): warning C4244: 'argument': conversion from 'double' to 'unsigned long', possible loss of data\n",
      "  src/ft2font_wrapper.cpp(98): warning C4244: 'argument': conversion from 'double' to 'unsigned long', possible loss of data\n",
      "  src/ft2font_wrapper.cpp(355): warning C4267: 'return': conversion from 'size_t' to 'unsigned long', possible loss of data\n",
      "  src/ft2font_wrapper.cpp(442): warning C4244: '=': conversion from 'Py_ssize_t' to 'FT_Long', possible loss of data\n",
      "  src/ft2font_wrapper.cpp(699): warning C4267: 'argument': conversion from 'size_t' to 'long', possible loss of data\n",
      "  src/ft2font_wrapper.cpp(902): warning C4244: 'argument': conversion from 'double' to 'int', possible loss of data\n",
      "  src/ft2font_wrapper.cpp(1767): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.\n",
      "  mplutils.cpp\n",
      "  py_converters.cpp\n",
      "     Creating library build\\temp.win-amd64-3.8\\Release\\src\\ft2font.cp38-win_amd64.lib and object build\\temp.win-amd64-3.8\\Release\\src\\ft2font.cp38-win_amd64.exp\n",
      "  Generating code\n",
      "  Finished generating code\n",
      "  building 'matplotlib._png' extension\n",
      "  _png.cpp\n",
      "  src/_png.cpp(335): warning C4244: 'argument': conversion from 'Py_ssize_t' to 'int', possible loss of data\n",
      "  src/_png.cpp(317): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.\n",
      "  checkdep_libpng.c\n",
      "  Compiling with libpng version 1.6.37.\n",
      "  mplutils.cpp\n",
      "  LINK : fatal error LNK1181: cannot open input file 'png.lib'\n",
      "  error: command 'C:\\\\Program Files\\\\Microsoft Visual Studio\\\\2022\\\\Community\\\\VC\\\\Tools\\\\MSVC\\\\14.30.30705\\\\bin\\\\HostX86\\\\x64\\\\link.exe' failed with exit code 1181\n",
      "  [end of output]\n",
      "  \n",
      "  note: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "  WARNING: No metadata found in c:\\users\\aratr\\anaconda3\\lib\\site-packages\n",
      "error: legacy-install-failure\n",
      "\n",
      "Encountered error while trying to install package.\n",
      "\n",
      "matplotlib\n",
      "\n",
      "note: This is an issue with the package mentioned above, not pip.\n",
      "hint: See above for output from the failure.\n"
     ]
    }
   ],
   "source": [
    "!pip install pdpbox"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "bb46be35",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
